### ISSUE TITLE
Current scoring methodology

### ISSUE THREAD

**Issue by RichardRed0x** [CoindeskData/CEX-Methodology#2]
This is a great initiative to make your methodology more open. 

I wanted to make sure I understand the scoring as it currently works. Is it based a count of the number of events, expressed as a percentage of the count for the top performing project (Bitcoin)? Then the overall score is a weighted average of those percentages according to the weights in methodology.json?

And these figures are totals for the history of the repository being watched?

**Comment by CoindeskData** [comment]
Yes, that's more or less it. However, 'top performing project' is where I would not agree. Bitcoin is used as a 'measuring stick', and there's no problem in our methodology with scoring above bitcoin. We expect this to happen as we extend the repos and projects we track on GitHub.

**Comment by RichardRed0x** [comment]
I wasn't sure if the total for a project was expressed as a percentage of the max figure, or relative to Bitcoin (which happens to have the highest numbers), so that clarification is helpful. Thanks.
